// src/components/AppLayout.vue
<script setup lang="ts"></script>

<template>
  <div class="app-layout" :class="{ background: true, 'no-background': false }">
    <div class="header">
      <slot name="header"></slot>
    </div>
    <div class="sidebar">
      <slot name="sidebar"></slot>
    </div>
    <div class="content" id="app-main-content">
      <slot name="content"></slot>
    </div>
  </div>
</template>

<style scoped>
.app-layout {
  @apply fixed inset-0;
  @apply grid grid-cols-[auto,1fr] grid-rows-[auto,1fr];
  @apply overflow-hidden;

  &.background {
    @apply bg-page-light bg-cover bg-center;
    @apply dark:bg-page-dark;
  }

  &.no-background {
    @apply bg-white dark:bg-gray-800;
  }
}

.header {
  @apply col-span-2;
}

.sidebar {
  @apply overflow-auto;
}

.content {
  @apply overflow-auto;
}
</style>

// src/components/App/AppLayout.tsx
import classNames from 'classnames'
import { FC, PropsWithChildren, ReactElement } from 'react'
import { useToggleBackground } from './useToggleBackground'

type Props = {
  header: ReactElement
  sidebar: ReactElement
}

export const AppLayout: FC<PropsWithChildren<Props>> = ({
  children,
  header,
  sidebar,
}) => {
  const toggleBackground = useToggleBackground()

  return (
    <div
      className={classNames(
        'fixed inset-0',
        'grid grid-cols-[auto,1fr] grid-rows-[auto,1fr]',
        'overflow-hidden',
        {
          'bg-page-light bg-cover bg-center dark:bg-page-dark':
            toggleBackground.showBackground,
          'bg-white dark:bg-gray-800': !toggleBackground.showBackground,
        },
      )}
    >
      <div className="col-span-2">{header}</div>
      <div className="overflow-auto">{sidebar}</div>
      <div className="overflow-auto" id="main-content">
        {children}
      </div>
    </div>
  )
}
