// src/app/AppLayout.tsx
import classNames from 'classnames'
import {
  type FC,
  type PropsWithChildren,
  type ReactElement,
  useRef,
} from 'react'
import {
  useShowJumpLinks,
  useShowJumpLinksMobile,
} from '../jump-links/useJumpLinks.ts'
import { useIsAppMode } from './appModeStore.ts'
import { useShowBackground } from './useBackgroundImage.ts'
import { useFocusAppLayoutElements } from './useFocusAppLayoutElements.ts'

type Props = {
  header: ReactElement
  sidebar: ReactElement
}

export const AppLayout: FC<PropsWithChildren<Props>> = ({
  children,
  header,
  sidebar,
}) => {
  const sidebarRef = useRef<HTMLDivElement>(null)
  const mainContentRef = useRef<HTMLDivElement>(null)

  const showBackground = useShowBackground()
  const showJumpLinks = useShowJumpLinks()
  const showJumpLinksMobile = useShowJumpLinksMobile()
  const isAppMode = useIsAppMode()

  useFocusAppLayoutElements({ sidebarRef, mainContentRef })

  return (
    <div
      className={classNames(
        'fixed inset-0 p-2',
        'grid grid-cols-1 grid-rows-[auto_1fr] gap-2',
        {
          'md:grid-cols-[auto_1fr]': showJumpLinks,
          'md:grid-cols-1': !showJumpLinks,
        },
        'overflow-hidden',
        {
          'bg-[url(/assets/images/background-light.jpg)] bg-cover bg-center dark:bg-[url(/assets/images/background-dark.jpg)]':
            showBackground,
          'bg-gray-200 dark:bg-gray-800': !showBackground,
        },
      )}
    >
      <div className="md:col-span-2">{header}</div>

      <div
        className={classNames([
          'overflow-auto rounded-xl bg-white/30 max-md:contents dark:bg-white/5',
          'outline-none',
          'ring-black/30 focus-within:ring-1 dark:ring-white/30',
          {
            'max-md:hidden': !showJumpLinksMobile,
            'md:hidden': !showJumpLinks || isAppMode('search'),
          },
        ])}
        ref={sidebarRef}
        tabIndex={0}
      >
        {sidebar}
      </div>

      <div
        className={classNames([
          'overflow-auto rounded-xl bg-white/30 dark:bg-white/5',
          'outline-none',
          'ring-black/30 focus-within:ring-1 dark:ring-white/30',
          {
            'row-start-2 md:col-span-2': !showJumpLinks || isAppMode('search'),
          },
        ])}
        id="main-content"
        ref={mainContentRef}
        tabIndex={0}
      >
        {children}
      </div>
    </div>
  )
}

// src/components/AppLayout.vue
<script setup lang="ts"></script>

<template>
  <div class="app-layout" :class="{ background: true, 'no-background': false }">
    <div class="header">
      <slot name="header"></slot>
    </div>
    <div class="sidebar">
      <slot name="sidebar"></slot>
    </div>
    <div class="content" id="app-main-content">
      <slot name="content"></slot>
    </div>
  </div>
</template>

<style scoped>
.app-layout {
  @apply fixed inset-0;
  @apply grid grid-cols-[auto,1fr] grid-rows-[auto,1fr];
  @apply overflow-hidden;

  &.background {
    @apply bg-page-light bg-cover bg-center;
    @apply dark:bg-page-dark;
  }

  &.no-background {
    @apply bg-white dark:bg-gray-800;
  }
}

.header {
  @apply col-span-2;
}

.sidebar {
  @apply overflow-auto;
}

.content {
  @apply overflow-auto;
}
</style>
